### ISSUE TITLE
Is this project still active and working with QEMU 6.1

### ISSUE THREAD

**Issue by BrendanSimon** [BrainwreckedTech/qemu-launcher#2]
Hi,

I came across this project, looking for a python based GUI (preferably Python >= 3.7, wxPython >= 4) for managing QEMU VMs.

Is this project still "active" (last commit was 2020) and is it known to work with QEMU 6.1

If not, are there any similar projects that might be of interest?

Thanks,
Brendan.

**Comment by BrainwreckedTech** [comment]
By default I'm hesitant to push changes until I've tested them for a while.  But this project hardly gets any feedback and that makes me even lazier about pusing changes.

There's been significant changes to the script that I should probably push out.  The GUI part will be going away.
